# config.yaml

seed: 42
environments:
  - CartPole-v1
  - MountainCar-v0
  - LunarLander-v3
  - Pendulum-v1
  - Acrobot-v1
algorithms:
  - DQN
  - DoubleDQN
  - DuelingDQN          # Optional
training:
  episodes: 1000
  batch_size: 64
  gamma: 0.99
  learning_rate: 1e-3
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 500
  target_update: 10
replay_buffer:
  capacity: 10000
